Implement e2e to validate module's install process
leonampd/magento2 pull request #2
Opened 2018-03-09 14:52 UTC by leonampd

Creates a new context to test if the module is installed correctly. It tests if a given ecommerce admin can log in admin panel and checks if a module menu item is visible on sidebar menu

2018-03-09 15:29 UTC, lflimeira requested changes
I think we should implement CI before we approve.

2018-03-09 15:29 UTC, lflimeira commented on Test/Acceptance/AdminContext.php
> +        $this->getSession()->wait(
We could implement a Spin method and stop to use the wait method =)

2018-03-09 15:29 UTC, lflimeira commented on Test/Acceptance/AdminContext.php
> +        return '#menu-mundipagg-top-level';
There isn't another property that doesn't have mundipagg?

2018-03-09 15:38 UTC, leonampd commented on Test/Acceptance/AdminContext.php
> +        $this->getSession()->wait(
In this case the spin already implemented, isn't it? I mean, the second paramenter is a condition that checks if the page has been loaded.

2018-03-09 20:27 UTC, lflimeira approved these changes

2018-03-13 18:12 UTC, lflimeira approved these changes

2018-03-13 19:42 UTC, merged